### ISSUE TITLE
[Bug] AttributeError

### ISSUE THREAD

**Issue by natowi** [CheshireCC/fatser-whisper-GUI#10]
在尝试保存文件时，我遇到了一些错误：

version: 11070
torchaudio_cuda_version: 11070
_lfilter_core_cpu_loop:torchaudio._lfilter_core_loop
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
torchvision is not available - cannot save figures
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
language: en_GB

Traceback (most recent call last):
  File "C:\FASTER~1\qfluentwidgets\components\navigation\navigation_panel.py", line 506, in _onWidgetClicked
AttributeError: 'NoneType' object has no attribute 'isSelectable'
Traceback (most recent call last):
  File "C:\FASTER~1\qfluentwidgets\components\navigation\navigation_panel.py", line 506, in _onWidgetClicked
AttributeError: 'NoneType' object has no attribute 'isSelectable'
Traceback (most recent call last):
  File "C:\FASTER~1\qfluentwidgets\components\navigation\navigation_panel.py", line 506, in _onWidgetClicked
AttributeError: 'NoneType' object has no attribute 'isSelectable'

==========Speaker_Diarize==========

Speaker diarize and alignment
load speaker brain model...
failed to diarize speaker!
Error: No module named 'asteroid_filterbanks'
UPdata DataModel

==========OutputSubtitleFiles==========

【Over】
Traceback (most recent call last):
  File "C:\FASTER~1\qfluentwidgets\components\navigation\navigation_panel.py", line 506, in _onWidgetClicked
AttributeError: 'NoneType' object has no attribute 'isSelectable'

---
----
这有时会导致崩溃

**Comment by CheshireCC** [comment]
You failed to use the "speaker separation" function. According to the log file information, you seem to have lost some modules. There may be something wrong with your installation, resulting in some files of the program not being copied correctly to your computer. It is recommended that you completely clear all files in the installation directory after uninstalling the software (the cache folder can be retained, which may contain the downloaded model file cache). Then reinstall version 0.3.0
